# Actions workflow for testing the Django project

name: Django project tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    services:
      db:
        image: postgres:9.6.17-alpine
        env:
          POSTGRES_DB: socialNetwork
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: socialNetwork
          POSTGRES_PORT: 5432
        ports:
          - 5432

      ganache:
        image: trufflesuite/ganache-cli:latest
        ports:
          - 8545:8545

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '12'  

    - name: Check node and npm versions
      working-directory: ./blockchain
      run: echo "node version $(node --version)" && echo "npm version $(npm --version)"
    
    - name: Install truffle
      working-directory: ./blockchain
      run: npm install -g truffle

    - name: Deploy SC
      working-directory: ./blockchain
      run: truffle deploy

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
        
    - name: Install Django requirements
      env:
        CI: On
      working-directory: ./socialNetwork
      run: pip install -r requirements.txt
        
    - name: Run tests and coverage
      env:
        CI: On
      working-directory: ./socialNetwork
      run: coverage run manage.py test

    - name: Run coverage report
      working-directory: ./socialNetwork
      run: coverage report
