# Actions workflow for testing the Smart Contract/s

name: Smart Contracts tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.4.2
      
    - name: Install docker
      run: sudo apt install docker

    - name: Start ganache-cli docker
      run: docker run -d -p 8545:8545 trufflesuite/ganache-cli:latest
    
    - name: Install truffle
      run: sudo npm install -g truffle

    - name: Install truffle-assertion
      working-directory: ./blockchain
      run: sudo npm install truffle-assertions

    - name: Configure truffle permission
      run: sudo chmod -R --silent 777 ~/.config/truffle
         
    - name: Run tests
      working-directory: ./blockchain
      run: truffle test
