# Actions workflow for testing the Smart Contract/s

name: Smart Contracts tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
      
    - name: Check node and npm versions
      working-directory: ./blockchain
      run: echo "node version $(node --version)" && echo "npm version $(npm --version)"

    - name: Install docker
      run: apt install docker

    - name: Start ganache-cli docker
      run: docker run -d -p 8545:8545 trufflesuite/ganache-cli:latest
    
    - name: Install truffle
      working-directory: ./blockchain
      run: npm install -g truffle

    # - name: Configure truffle permission
    #  run: sudo chmod -R --silent 777 ~/.config/truffle

    - name: Install npm dependencies
      working-directory: ./blockchain
      run: npm install 

    - name: Create needed file
      working-directory: ./blockchain
      run: |
        mkdir -p build/contracts
        touch build/contracts/SocialNetwork-address

    - name: Run tests
      working-directory: ./blockchain
      run: npm test

    - name: Run coverage
      working-directory: ./blockchain
      run: npm run-script coverage

