# Actions workflow for testing the Smart Contract/s

name: Smart Contracts tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build_and_test:
    runs-on: ubuntu-16.04

    services:
      ganache:
        image: trufflesuite/ganache-cli:latest
        ports:
          - 8545:8545
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Check node and npm versions
      working-directory: ./blockchain
      run: echo "node version $(node --version)" && echo "npm version $(npm --version)"
    
    - name: Install truffle
      working-directory: ./blockchain
      run: npm install -g truffle

    # - name: Configure truffle permission
    #  run: sudo chmod -R --silent 777 ~/.config/truffle

    - name: Install npm dependencies
      working-directory: ./blockchain
      run: sudo npm install 

    - name: Create needed file
      working-directory: ./blockchain
      run: |
        mkdir -p build/contracts
        touch build/contracts/SocialNetwork-address

    - name: Run tests
      working-directory: ./blockchain
      run: npm test

    - name: Run coverage
      working-directory: ./blockchain
      run: npm run-script coverage

