# This is a basic workflow to help you get started with Actions

name: Smart Contractc tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.4.2
      
    # Runs a single command using the runners shell
    - name: Install docker
      run: sudo apt install docker

    # Runs a single command using the runners shell
    - name: Start ganache-cli docker
      run: docker run -d -p 8545:8545 trufflesuite/ganache-cli:latest
    
    # Runs a single command using the runners shell
    - name: Install truffle
      run: sudo npm install -g truffle

    # Runs a single command using the runners shell
    - name: Install truffle-assertion
      working-directory: ./blockchain
      run: sudo npm install truffle-assertions

    # Runs a single command using the runners shell
    - name: Configure truffle permission
      run: sudo chmod -R --silent 777 ~/.config/truffle
         
     # Runs a single command using the runners shell
    - name: Run tests
      working-directory: ./blockchain
      run: truffle test
